Many changes: cleanup, refactoring. Added additional runner scripts.

diff --git a/iPCR/iPCR-mark_duplicates b/iPCR/iPCR-mark_duplicates
--- a/iPCR/iPCR-mark_duplicates
+++ b/iPCR/iPCR-mark_duplicates
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+#-------------------------------------------------------------------------------#
+#                            Script global Settings                             #
+#-------------------------------------------------------------------------------#
 # Version info
 SCRIPTNAME=iPCR-extract_target_regions.sh
 VERSION=0.0.1
@@ -13,7 +16,15 @@ LOG=false
 # Tools
 PICARD="java -XX:ParallelGCThreads=1 -Xmx4g -jar \${EBROOTPICARD}/picard.jar"
 
-# PARSE OPTIONS
+# If any command fails, fail the entire script
+set -e
+
+# Log the starttime
+starttime=$(date +%s)
+
+#-------------------------------------------------------------------------------#
+#                                 Parse options                                 #
+#-------------------------------------------------------------------------------#
 OPTIND=1         # Reset in case getopts has been used previously in the shell.
 USAGE=
 usage() {
@@ -64,10 +75,10 @@ while getopts "h?o:r:i:l:b:n:c" opt; do
 done
 shift $(( OPTIND - 1 ))
 
-
-starttime=$(date +%s)
-
-#Check all required options are set
+#-------------------------------------------------------------------------------#
+#                              IO definitions                                   #
+#-------------------------------------------------------------------------------#
+# Check all required options are set
 if [ -z ${OUTDIR+x} ]; then echo "option -o not set (directory for output files)"; usage; exit 1; fi
 if [ -z ${BASENAME+x} ]; then
   # Create BASENAME based on 1st input fastq filename remove ".fastq.*" (or ".fq.*") from filename
@@ -84,6 +95,16 @@ if [ ${LOG} == "true" ]; then
   exec 2>&1
 fi
 
+# Check if script has been run succesfully previously
+if [ -f "${OUTDIR}/${BASENAME}.done" ]; then
+  echo "[WARN - $(date '+%Y-%m-%d %H:%M:%S')] Overwriting previous results"
+  rm "${OUTDIR}/${BASENAME}.done"
+fi
+
+#-------------------------------------------------------------------------------#
+#                              Main program loop                                #
+#-------------------------------------------------------------------------------#
+# Mark duplicate mapped reads
 PICARD_CMD="${PICARD} \
 MarkDuplicates \
 I=${INPUT_BAM} \
@@ -100,3 +121,14 @@ eval $PICARD_CMD
 
 echo "=========================================================================="
 echo "[INFO - $(date '+%Y-%m-%d %H:%M:%S')] script ran for $(( ($(date +%s) - ${starttime}) / 60)) minutes"
+
+# Log the TMP or intermediate files not critical for the output to the done file
+# These can then be cleaned later or right away if -c is specified
+echo "" > ${OUTDIR}/${BASENAME}.done
+
+if [ ${CLEAN} == "true" ]; then
+  echo "[INFO - $(date '+%Y-%m-%d %H:%M:%S')] Cleaning intermediate files"
+  # Could loop over the .done file, but for safety's sake ill did it like this, to avoid any mishaps
+fi
+
+echo "[INFO - $(date '+%Y-%m-%d %H:%M:%S')] Done"
